// fa2db635-13a1-45ad-9b4e-4a954df7045d/src/components/layout/AppLayout.vue
<script setup lang="ts">
import Sidebar from './Sidebar.vue'
import Topbar from './Topbar.vue'
import MobileTabBar from './MobileTabBar.vue'
</script>

<template>
  <div class="min-h-screen flex">
    <Sidebar />
    <div class="flex-1 min-w-0 flex flex-col">
      <Topbar />
      <main class="flex-1 px-4 lg:px-8 py-6 pb-24 lg:pb-8 max-w-[1600px] w-full mx-auto">
        <RouterView />
      </main>
    </div>
    <MobileTabBar />
  </div>
</template>

// df95c352-b9f9-46e6-b1e7-672ec4c41d9a/src/components/Layout/AppLayout.tsx
import { Outlet } from "react-router-dom";
import Sidebar from "./Sidebar";
import RightPanel from "./RightPanel";

export default function AppLayout() {
  return (
    <div className="flex h-screen w-full overflow-hidden bg-background">
      <Sidebar />
      <main className="flex min-w-0 flex-1 flex-col">
        <div className="flex-1 overflow-y-auto scrollbar-thin">
          <Outlet />
        </div>
      </main>
      <RightPanel />
    </div>
  );
}
