// fa2db635-13a1-45ad-9b4e-4a954df7045d/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'
import { MENU_GROUPS } from '@/constants'
import DynamicIcon from '@/components/ui/DynamicIcon.vue'
import { Sparkles } from 'lucide-vue-next'

const route = useRoute()
const router = useRouter()

function go(path: string) {
  router.push(path)
}
</script>

<template>
  <aside class="hidden lg:flex flex-col w-60 shrink-0 h-screen sticky top-0 bg-wine-grad text-white/90">
    <div class="px-6 py-6 flex items-center gap-2.5 border-b border-white/10">
      <div class="w-9 h-9 rounded-xl bg-gold-grad flex items-center justify-center shadow-soft">
        <Sparkles :size="18" class="text-wine-800" />
      </div>
      <div>
        <p class="font-display text-xl font-semibold leading-none text-white">锦时</p>
        <p class="text-[10px] tracking-[0.2em] text-gold-200 mt-1">WEDDING SUITE</p>
      </div>
    </div>

    <nav class="flex-1 overflow-y-auto px-3 py-4 space-y-5">
      <div v-for="group in MENU_GROUPS" :key="group.group">
        <p class="px-3 mb-1.5 text-[10px] tracking-widest text-white/40 uppercase">{{ group.group }}</p>
        <button
          v-for="item in group.items"
          :key="item.key"
          @click="go(item.path)"
          class="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-all duration-200"
          :class="route.path.startsWith(item.path) ? 'bg-white/15 text-white shadow-soft' : 'text-white/70 hover:bg-white/8 hover:text-white'"
        >
          <DynamicIcon :name="item.icon" :size="17" />
          <span>{{ item.label }}</span>
          <span v-if="route.path.startsWith(item.path)" class="ml-auto w-1 h-4 rounded-full bg-gold-grad"></span>
        </button>
      </div>
    </nav>

    <div class="px-4 py-4 border-t border-white/10 text-[11px] text-white/40">
      <p>锦时婚礼管家 v1.0</p>
      <p class="mt-0.5">© 2026 锦时集团</p>
    </div>
  </aside>
</template>

// 94c284b2-3ceb-4851-a8d4-f94b6dde7372/frontend/src/components/Sidebar.tsx
import { useLocation, useNavigate } from 'react-router-dom';
import {
  LayoutDashboard,
  Calendar,
  Users,
  AlertTriangle,
  BarChart3,
  Settings,
  ChevronLeft,
  ChevronRight,
  Brain,
} from 'lucide-react';
import { useAppStore } from '@/store';
import clsx from 'clsx';

const navItems = [
  { path: '/', label: '工作台', icon: LayoutDashboard },
  { path: '/appointments', label: '预约管理', icon: Calendar },
  { path: '/patients', label: '患者档案', icon: Users },
  { path: '/warnings', label: '预警中心', icon: AlertTriangle, badge: 'pendingWarningCount' },
  { path: '/statistics', label: '统计报表', icon: BarChart3 },
  { path: '/settings', label: '系统设置', icon: Settings },
];

export default function Sidebar() {
  const location = useLocation();
  const navigate = useNavigate();
  const { sidebarCollapsed, toggleSidebar, pendingWarningCount } = useAppStore();

  return (
    <aside
      className={clsx(
        'fixed left-0 top-0 z-30 h-full bg-white border-r border-gray-200 flex flex-col transition-all duration-200',
        sidebarCollapsed ? 'w-16' : 'w-60',
      )}
    >
      <div className="h-16 flex items-center justify-between px-4 border-b border-gray-100">
        <div className="flex items-center gap-2 overflow-hidden">
          <div className="w-8 h-8 rounded-lg bg-primary-600 flex items-center justify-center flex-shrink-0">
            <Brain className="w-5 h-5 text-white" />
          </div>
          {!sidebarCollapsed && (
            <span className="font-semibold text-gray-800 whitespace-nowrap">精神卫生中心</span>
          )}
        </div>
      </div>

      <nav className="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
        {navItems.map((item) => {
          const Icon = item.icon;
          const isActive =
            item.path === '/' ? location.pathname === '/' : location.pathname.startsWith(item.path);
          const showBadge = item.badge === 'pendingWarningCount' && pendingWarningCount > 0;

          return (
            <div
              key={item.path}
              onClick={() => navigate(item.path)}
              className={clsx('nav-item relative', isActive && 'nav-item-active')}
              title={sidebarCollapsed ? item.label : undefined}
            >
              <Icon className="w-5 h-5 flex-shrink-0" />
              {!sidebarCollapsed && <span>{item.label}</span>}
              {showBadge && !sidebarCollapsed && (
                <span className="ml-auto badge bg-danger-100 text-danger-600 animate-pulse-badge">
                  {pendingWarningCount > 99 ? '99+' : pendingWarningCount}
                </span>
              )}
              {showBadge && sidebarCollapsed && (
                <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-danger-500 rounded-full animate-pulse-badge" />
              )}
            </div>
          );
        })}
      </nav>

      <div className="p-3 border-t border-gray-100">
        <button onClick={toggleSidebar} className="nav-item w-full justify-center" title="折叠/展开">
          {sidebarCollapsed ? <ChevronRight className="w-5 h-5" /> : <ChevronLeft className="w-5 h-5" />}
          {!sidebarCollapsed && <span>收起菜单</span>}
        </button>
      </div>
    </aside>
  );
}
