// fa2db635-13a1-45ad-9b4e-4a954df7045d/src/components/layout/Topbar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { Bell, Search, ChevronDown, LogOut, Plus } from 'lucide-vue-next'

const auth = useAuthStore()
const router = useRouter()
const showMenu = ref(false)

function logout() {
  auth.logout()
  router.push('/login')
}

function createWedding() {
  router.push('/weddings/create')
}
</script>

<template>
  <header class="sticky top-0 z-30 flex items-center gap-3 px-4 lg:px-8 h-16 bg-cream/80 backdrop-blur-md border-b border-wine-100">
    <div class="flex-1 flex items-center gap-3">
      <div class="relative max-w-md w-full hidden sm:block">
        <Search :size="16" class="absolute left-3 top-1/2 -translate-y-1/2 text-wine-300" />
        <input class="field-input pl-9 h-9 bg-white/70" placeholder="搜索婚礼、新人、合同…" />
      </div>
    </div>

    <button class="btn-primary h-9 px-3 text-sm" @click="createWedding">
      <Plus :size="16" /> <span class="hidden sm:inline">创建婚礼</span>
    </button>

    <button class="relative w-9 h-9 rounded-lg hover:bg-white/60 flex items-center justify-center text-wine-600 transition">
      <Bell :size="18" />
      <span class="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-rose-500 ring-2 ring-cream"></span>
    </button>

    <div class="relative">
      <button class="flex items-center gap-2 pl-1 pr-2 h-9 rounded-lg hover:bg-white/60 transition" @click="showMenu = !showMenu">
        <div class="w-7 h-7 rounded-full bg-wine-grad text-white text-xs flex items-center justify-center font-medium">
          {{ auth.user?.name?.charAt(0) || '锦' }}
        </div>
        <div class="hidden sm:block text-left">
          <p class="text-xs font-medium text-wine-800 leading-none">{{ auth.user?.name }}</p>
          <p class="text-[10px] text-wine-400 mt-0.5">{{ auth.roleLabel }}</p>
        </div>
        <ChevronDown :size="14" class="text-wine-400" />
      </button>
      <transition name="fade">
        <div v-if="showMenu" class="absolute right-0 mt-2 w-44 card p-1.5 shadow-lift z-50" @click="showMenu = false">
          <button class="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm text-wine-700 hover:bg-wine-50 transition" @click="logout">
            <LogOut :size="15" /> 退出登录
          </button>
        </div>
      </transition>
    </div>
  </header>
</template>

// 94c284b2-3ceb-4851-a8d4-f94b6dde7372/frontend/src/components/Topbar.tsx
import { Bell, Search, User, LogOut, ChevronDown } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { useState } from 'react';
import { useAppStore } from '@/store';
import clsx from 'clsx';

const routeTitles: Record<string, string> = {
  '/': '工作台',
  '/appointments': '预约管理',
  '/patients': '患者档案',
  '/warnings': '预警中心',
  '/statistics': '统计报表',
  '/settings': '系统设置',
};

export default function Topbar() {
  const location = useLocation();
  const { user, pendingWarningCount, logout } = useAppStore();
  const [menuOpen, setMenuOpen] = useState(false);

  const pathKey = Object.keys(routeTitles).find(
    (k) => (k === '/' ? location.pathname === '/' : location.pathname.startsWith(k)),
  );
  const title = routeTitles[pathKey || '/'] || '';

  return (
    <header className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6 sticky top-0 z-20">
      <div className="flex items-center gap-2 text-sm text-gray-500">
        <span>首页</span>
        <ChevronDown className="w-4 h-4 -rotate-90" />
        <span className="text-gray-800 font-medium">{title}</span>
      </div>

      <div className="flex items-center gap-2">
        <div className="relative hidden md:block">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            placeholder="搜索患者、预约..."
            className="pl-9 pr-4 py-2 w-64 bg-gray-50 border border-gray-200 rounded text-sm focus:outline-none focus:border-primary-400 focus:bg-white transition-colors"
          />
        </div>

        <button className="relative p-2 rounded-lg hover:bg-gray-100 transition-colors">
          <Bell className="w-5 h-5 text-gray-600" />
          {pendingWarningCount > 0 && (
            <span className="absolute top-1 right-1 w-4 h-4 bg-danger-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center animate-pulse-badge">
              {pendingWarningCount > 9 ? '9+' : pendingWarningCount}
            </span>
          )}
        </button>

        <div className="relative ml-2">
          <button
            onClick={() => setMenuOpen(!menuOpen)}
            className="flex items-center gap-2 p-1.5 pr-3 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <div className="w-8 h-8 rounded-full bg-primary-100 flex items-center justify-center">
              <User className="w-4 h-4 text-primary-600" />
            </div>
            <span className="text-sm text-gray-700">{user?.name || '管理员'}</span>
            <ChevronDown className={clsx('w-4 h-4 text-gray-400 transition-transform', menuOpen && 'rotate-180')} />
          </button>
          {menuOpen && (
            <div className="absolute right-0 top-full mt-1 w-44 bg-white rounded-lg shadow-card-hover border border-gray-100 py-1 animate-fade-in">
              <button className="w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 text-left">个人设置</button>
              <button
                onClick={logout}
                className="w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 text-left flex items-center gap-2"
              >
                <LogOut className="w-4 h-4" /> 退出登录
              </button>
            </div>
          )}
        </div>
      </div>
    </header>
  );
}
