// 94c284b2-3ceb-4851-a8d4-f94b6dde7372/frontend/src/components/Sidebar.tsx
import { useLocation, useNavigate } from 'react-router-dom';
import {
  LayoutDashboard,
  Calendar,
  Users,
  AlertTriangle,
  BarChart3,
  Settings,
  ChevronLeft,
  ChevronRight,
  Brain,
} from 'lucide-react';
import { useAppStore } from '@/store';
import clsx from 'clsx';

const navItems = [
  { path: '/', label: '工作台', icon: LayoutDashboard },
  { path: '/appointments', label: '预约管理', icon: Calendar },
  { path: '/patients', label: '患者档案', icon: Users },
  { path: '/warnings', label: '预警中心', icon: AlertTriangle, badge: 'pendingWarningCount' },
  { path: '/statistics', label: '统计报表', icon: BarChart3 },
  { path: '/settings', label: '系统设置', icon: Settings },
];

export default function Sidebar() {
  const location = useLocation();
  const navigate = useNavigate();
  const { sidebarCollapsed, toggleSidebar, pendingWarningCount } = useAppStore();

  return (
    <aside
      className={clsx(
        'fixed left-0 top-0 z-30 h-full bg-white border-r border-gray-200 flex flex-col transition-all duration-200',
        sidebarCollapsed ? 'w-16' : 'w-60',
      )}
    >
      <div className="h-16 flex items-center justify-between px-4 border-b border-gray-100">
        <div className="flex items-center gap-2 overflow-hidden">
          <div className="w-8 h-8 rounded-lg bg-primary-600 flex items-center justify-center flex-shrink-0">
            <Brain className="w-5 h-5 text-white" />
          </div>
          {!sidebarCollapsed && (
            <span className="font-semibold text-gray-800 whitespace-nowrap">精神卫生中心</span>
          )}
        </div>
      </div>

      <nav className="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
        {navItems.map((item) => {
          const Icon = item.icon;
          const isActive =
            item.path === '/' ? location.pathname === '/' : location.pathname.startsWith(item.path);
          const showBadge = item.badge === 'pendingWarningCount' && pendingWarningCount > 0;

          return (
            <div
              key={item.path}
              onClick={() => navigate(item.path)}
              className={clsx('nav-item relative', isActive && 'nav-item-active')}
              title={sidebarCollapsed ? item.label : undefined}
            >
              <Icon className="w-5 h-5 flex-shrink-0" />
              {!sidebarCollapsed && <span>{item.label}</span>}
              {showBadge && !sidebarCollapsed && (
                <span className="ml-auto badge bg-danger-100 text-danger-600 animate-pulse-badge">
                  {pendingWarningCount > 99 ? '99+' : pendingWarningCount}
                </span>
              )}
              {showBadge && sidebarCollapsed && (
                <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-danger-500 rounded-full animate-pulse-badge" />
              )}
            </div>
          );
        })}
      </nav>

      <div className="p-3 border-t border-gray-100">
        <button onClick={toggleSidebar} className="nav-item w-full justify-center" title="折叠/展开">
          {sidebarCollapsed ? <ChevronRight className="w-5 h-5" /> : <ChevronLeft className="w-5 h-5" />}
          {!sidebarCollapsed && <span>收起菜单</span>}
        </button>
      </div>
    </aside>
  );
}

// 89780ca8-47c1-4851-b43d-0c38fa724c20/frontend/src/components/Sidebar.vue
<template>
  <aside
    class="fixed left-0 top-0 h-full z-50 transition-all duration-300 flex flex-col"
    :class="collapsed ? 'w-[72px]' : 'w-[240px]'"
    style="background: rgba(10, 14, 39, 0.95); border-right: 1px solid var(--border-color);"
  >
    <div class="flex items-center h-16 px-4 border-b" style="border-color: var(--border-color);">
      <div class="w-9 h-9 rounded-lg flex items-center justify-center" style="background: linear-gradient(135deg, var(--gold), var(--gold-light));">
        <span class="text-lg font-bold" style="color: var(--bg-deep);">N</span>
      </div>
      <span v-if="!collapsed" class="ml-3 text-lg font-semibold" style="font-family: 'Playfair Display', serif; color: var(--gold);">NexusTrade</span>
    </div>

    <nav class="flex-1 py-4 px-2 space-y-1">
      <router-link
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        class="flex items-center px-3 py-3 rounded-lg transition-all duration-200 group"
        :class="isActive(item.path) ? 'bg-opacity-20' : 'hover:bg-opacity-10'"
        :style="isActive(item.path) ? 'background: rgba(212, 168, 83, 0.15); color: var(--gold);' : 'color: var(--text-secondary);'"
        @mouseenter="(e: MouseEvent) => { if (!isActive(item.path)) (e.currentTarget as HTMLElement).style.color = 'var(--text-primary)' }"
        @mouseleave="(e: MouseEvent) => { if (!isActive(item.path)) (e.currentTarget as HTMLElement).style.color = 'var(--text-secondary)' }"
      >
        <component :is="item.icon" :size="20" />
        <span v-if="!collapsed" class="ml-3 text-sm font-medium">{{ item.label }}</span>
        <div
          v-if="isActive(item.path)"
          class="absolute left-0 w-1 h-6 rounded-r-full"
          style="background: var(--gold);"
        />
      </router-link>
    </nav>

    <div class="p-3 border-t" style="border-color: var(--border-color);">
      <button
        class="w-full flex items-center justify-center p-2 rounded-lg transition-colors"
        style="color: var(--text-secondary);"
        @click="$emit('toggle')"
      >
        <ChevronLeft :size="18" :class="{ 'rotate-180': collapsed }" class="transition-transform" />
      </button>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { useRoute } from 'vue-router'
import { ShoppingBag, Wallet, Palette, BarChart3, Shield, ChevronLeft } from 'lucide-vue-next'

defineProps<{ collapsed: boolean }>()
defineEmits<{ toggle: [] }>()

const route = useRoute()

const navItems = [
  { label: 'Market', path: '/', icon: ShoppingBag },
  { label: 'Assets', path: '/assets', icon: Wallet },
  { label: 'Creator', path: '/creator', icon: Palette },
  { label: 'Statistics', path: '/statistics', icon: BarChart3 },
  { label: 'Risk', path: '/risk', icon: Shield },
]

function isActive(path: string): boolean {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}
</script>
